version: '3'

services:
  web:
    build:
      context: ./frobshop
      dockerfile: Dockerfile
    container_name: web_frobshop
    volumes:
      - ./frobshop:/app
    expose:
      - 8000
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: db_frobshop
    restart: unless-stopped
    environment:
      - POSTGRES_DB=django_oscar
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=oscar
  nginx:
    build: ./nginx
    container_name: nginx_frobshop
    volumes:
      - ./frobshop/staticfiles:/app/staticfiles
      - ./frobshop/mediafiles:/app/mediafiles
    ports:
      - "127.0.0.1:1777:80"
    depends_on:
      - web
    restart: unless-stopped