# Generated by Django 3.2.14 on 2023-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200801_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_sync',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Sync QR code pic in binary format'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code_sync_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Sync QR code date written'),
        ),
    ]
