apiVersion: v1
kind: Service
metadata:
  name: frobshop-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: frobshop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000