apiVersion: v1
kind: Service
metadata:
  name: frobshop-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/api"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "7"
spec:
  type: LoadBalancer
  selector:
    app: frobshop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: qrcode-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/qrcode?data=1"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "7"
spec:
  type: LoadBalancer
  selector:
    app: qrcode
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: locust-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "7"
spec:
  type: LoadBalancer
  selector:
    app: locust
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8089