apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frobshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frobshop
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qrcode
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qrcode
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70