apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-app
  labels:
    app: qrcode
spec:
  selector:
    matchLabels:
      app: qrcode
  template:
    metadata:
      labels:
        app: qrcode
    spec:
      containers:
        - image: aaldaber/qrcode:latest
          name: qrcode
          ports:
            - containerPort: 8000
              name: gunicorn
          resources:
            requests:
              cpu: 100m